### ISSUE TITLE
Error : trying to open unclosed connection

### ISSUE THREAD

**Issue by 4fath** [mongolab/mongodb-driver-examples#5]
when i try to run that example i got this error : Trying to open unclosed connection .i am using last version both mongoose and express
here my code : 
`var mongoose = require('mongoose');`
`var mongoUrl = 'mongodb://username:password@ds013848.mlab.com:13848/notion_follow';`
`mongoose.connect(mongoUrl);`  // error on this line 
`var db = mongoose.connection;`

whats wrong on it ?

**Comment by Mintaka** [comment]
Hi
Hope You used right information instead of string "username" and "password".

Also error message will be helpfull.

**Comment by 4fath** [comment]
@Mintaka yes i used rigth info, actually i can access using command line. 
I tried createConnection but i got error again but diffrent. Finally i figure out where i am wrong , i use two times mongoose.connecton different place so i delete one , fixed the issue :)
